### PR TITLE
Add pan annotation html documentation generator

### PR DESCRIPTION
**Pull request by jrha**
THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE
AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS
SOFTWARE:

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND
CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE AND ANY WARRANTY OF NON-
INFRINGEMENT, ARE DISCLAIMED.

IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS
ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT
DISCLAIMER AS WELL AS ANY OTHER LICENSE TERMS THAT MAY
APPLY.

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha given this is not your code, do you want a review of it anyway?

**Comment by jrha** [comment]
Meh, it wouldn't hurt. It would probably be better to get it in and get @wdpypere hacking on it though...

**Comment by wdpypere** [comment]
looks nice! Ran it against our quattor templates and it generates nice documentation. however I tried it with the ncm-ceph schema ( ```target/pan/components/ceph/schema.pan``` because it has annotations) in configuration-modules-core but it does not do anything with the annotations. Maybe they are implemented wrong. I'll have a deeper look next week or so.

**Comment by jrha** [comment]
@wdpypere feel free to merge when you are happy.

**Comment by jrha** [comment]
Merged base code as is, @wdpypere can open PRs when he has improvements etc.

**Pull request merged**
