### PR TITLE
OneFlow description for build_all_repos

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha @alvarosimon feedback please

**Comment by alvarosimon** [comment]
@stdweird @jrha we still need to upload CentOS5 image to a public repo. For testing purposes I have used my own computer at home but the link is not available right now.. Do you know a good place to upload this image?

**Comment by jrha** [comment]
No sorry, @apdibbo?

**Comment by apdibbo** [comment]
Nowhere springs to mind

**Comment by ned21** [comment]
@stdweird to remove change to build_all_repos.sh that is no longer required and rebase on master, and then this can be merged.

**Pull request merged**
