### PR TITLE
 move documentation to RST

### PR DESCRIPTION
**Pull request by wdpypere**
@jrha this is what I updated 2 years ago. I will doublecheck what it actually outputs.

### CODE REVIEW

**Comment by wdpypere** [comment]
@jrha So this was used to build https://docs-test-comps.readthedocs.io/en/latest/ . any comments about the code or "new" website would be appreciated.

**Comment by jrha** [comment]
This is clearly a huge improvement, thanks!

**Comment by wdpypere** [comment]
@jrha I'm working on another update which will support template-library-core as well. When that is finished we can have a look at setting a date for switching.

**Comment by jrha** [comment]
Fantastic, thanks!

**Pull request merged**
