### PR TITLE
Documentation-builder: rework to be more agnostic

### PR DESCRIPTION
**Pull request by wdpypere**
- allows exports of variable annotations
 - a lot of the assumptions originally made for configuration-modules-core are taken out and made configurable

### CODE REVIEW

**Comment by jrha** [comment]
I've read through the code (as much as I could) and tested this on a development system, a few observations:
1. Not all of the run-time dependencies are obviously documented, on CentOS 7 I had to:
   ```sh
   cpan install Pod::Markdown
   cpan install Pod::POM::View::Restructured
   pip install -U Sphinx
   yum install htop
   yum install mkdocs
   yum install python2-devel
   yum install python2-mock
   yum install python2-pip
   yum install rubygem-bundler
   ```

2. The README doesn't seem to match the options available with `--help` anymore?
3. The build script is hard-coded to call `firefox` which is a fun surprise if it is not available, I symlinked this to `echo` on my headless build systems.
4. I couldn't get it to work with Python 3, I didn't spend too long on it, but it looks like it is related to something in the `vsc` libraries rather than this script.

**Comment by jrha** [comment]
But on the plus side, it generated beautiful documentation!

**Comment by jrha** [comment]
I will use this to generate the 19.12 docs and may well merge after that.

**Comment by wdpypere** [comment]
@jrha thanks for picking this up!

**Pull request merged**
