### PR TITLE
build_all_repos: build aquilon-protocols and aquilon on el7

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha i'm still fighting with running the aq unittests, so they are disabled for now

**Comment by jrha** [comment]
@stdweird they will take ~45mins if they run correctly, so it would be good not to have to run them every time I need a development system.

**Comment by stdweird** [comment]
@jrha last commit fixes an issue when build_all_repos thinks that the mocked `File::AtomicWrite` form `CAF` resources provides the actual `File::AtomicWrite` and thus doesn't try to install it, leading to failure

**Comment by jrha** [comment]
@stdweird this should probably be merged before any more conflicts arise, could you rebase it on master?

**Comment by stdweird** [comment]
@jrha rebased

**Comment by jrha** [comment]
Closed in 25b3b0bd7f1fbee0728c3ed4a6cd6cfbfcd24c36.

**Pull request closed without merging**
